# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\20212\software\implement\CIMS_project\UI\LoginError.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginError(object):
    def setupUi(self, LoginError):
        LoginError.setObjectName("LoginError")
        LoginError.resize(380, 250)
        self.OkButton = QtWidgets.QPushButton(LoginError)
        self.OkButton.setGeometry(QtCore.QRect(110, 140, 141, 51))
        self.OkButton.setObjectName("OkButton")
        self.label = QtWidgets.QLabel(LoginError)
        self.label.setGeometry(QtCore.QRect(30, 50, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        self.retranslateUi(LoginError)
        QtCore.QMetaObject.connectSlotsByName(LoginError)

    def retranslateUi(self, LoginError):
        _translate = QtCore.QCoreApplication.translate
        LoginError.setWindowTitle(_translate("LoginError", "LoginError"))
        self.OkButton.setText(_translate("LoginError", "확인"))
        self.label.setText(_translate("LoginError", "아이디 혹은 비밀번호가 틀렸습니다"))
