# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\20212\software\implement\CIMS_project\UI\Report List.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportList(object):
    def setupUi(self, ReportList):
        ReportList.setObjectName("ReportList")
        ReportList.resize(681, 640)
        self.SearchButton = QtWidgets.QPushButton(ReportList)
        self.SearchButton.setGeometry(QtCore.QRect(530, 560, 131, 61))
        self.SearchButton.setObjectName("SearchButton")
        self.textBrowser = QtWidgets.QTextBrowser(ReportList)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 621, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.ReportListScroll = QtWidgets.QSlider(ReportList)
        self.ReportListScroll.setGeometry(QtCore.QRect(650, 20, 22, 521))
        self.ReportListScroll.setOrientation(QtCore.Qt.Vertical)
        self.ReportListScroll.setObjectName("ReportListScroll")

        self.retranslateUi(ReportList)
        QtCore.QMetaObject.connectSlotsByName(ReportList)

    def retranslateUi(self, ReportList):
        _translate = QtCore.QCoreApplication.translate
        ReportList.setWindowTitle(_translate("ReportList", "ReportList"))
        self.SearchButton.setText(_translate("ReportList", "Search"))
