# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\20212\software\implement\CIMS_project\UI\Report.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportDialog(object):
    def setupUi(self, ReportDialog):
        ReportDialog.setObjectName("ReportDialog")
        ReportDialog.resize(1064, 756)
        self.TitleLineEdit = QtWidgets.QLineEdit(ReportDialog)
        self.TitleLineEdit.setGeometry(QtCore.QRect(140, 160, 811, 41))
        self.TitleLineEdit.setObjectName("TitleLineEdit")
        self.label = QtWidgets.QLabel(ReportDialog)
        self.label.setGeometry(QtCore.QRect(40, 160, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.ContentsTextEdit = QtWidgets.QTextEdit(ReportDialog)
        self.ContentsTextEdit.setGeometry(QtCore.QRect(140, 250, 811, 381))
        self.ContentsTextEdit.setObjectName("ContentsTextEdit")
        self.CancleButton = QtWidgets.QPushButton(ReportDialog)
        self.CancleButton.setGeometry(QtCore.QRect(700, 640, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.CancleButton.setFont(font)
        self.CancleButton.setObjectName("CancleButton")
        self.label_2 = QtWidgets.QLabel(ReportDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 250, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.ReportButton_2 = QtWidgets.QPushButton(ReportDialog)
        self.ReportButton_2.setGeometry(QtCore.QRect(830, 640, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.ReportButton_2.setFont(font)
        self.ReportButton_2.setObjectName("ReportButton_2")
        self.ReportLabel = QtWidgets.QLabel(ReportDialog)
        self.ReportLabel.setGeometry(QtCore.QRect(30, 50, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.ReportLabel.setFont(font)
        self.ReportLabel.setObjectName("ReportLabel")

        self.retranslateUi(ReportDialog)
        QtCore.QMetaObject.connectSlotsByName(ReportDialog)

    def retranslateUi(self, ReportDialog):
        _translate = QtCore.QCoreApplication.translate
        ReportDialog.setWindowTitle(_translate("ReportDialog", "Report"))
        self.label.setText(_translate("ReportDialog", "Title :"))
        self.CancleButton.setText(_translate("ReportDialog", "Cancle"))
        self.label_2.setText(_translate("ReportDialog", "Contents :"))
        self.ReportButton_2.setText(_translate("ReportDialog", "Report"))
        self.ReportLabel.setText(_translate("ReportDialog", "Report"))
