# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\20212\software\implement\CIMS_project\UI\SignIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignIn(object):
    def setupUi(self, SignIn):
        SignIn.setObjectName("SignIn")
        SignIn.setEnabled(True)
        SignIn.resize(1278, 720)
        SignIn.setMinimumSize(QtCore.QSize(0, 0))
        SignIn.setMaximumSize(QtCore.QSize(1278, 720))
        SignIn.setMouseTracking(False)
        SignIn.setTabletTracking(False)
        SignIn.setAnimated(True)
        SignIn.setDockNestingEnabled(False)
        SignIn.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(SignIn)
        self.centralwidget.setObjectName("centralwidget")
        self.CIMS = QtWidgets.QLabel(self.centralwidget)
        self.CIMS.setGeometry(QtCore.QRect(280, 120, 701, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.CIMS.setFont(font)
        self.CIMS.setAutoFillBackground(True)
        self.CIMS.setFrameShape(QtWidgets.QFrame.Panel)
        self.CIMS.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CIMS.setScaledContents(False)
        self.CIMS.setAlignment(QtCore.Qt.AlignCenter)
        self.CIMS.setIndent(-1)
        self.CIMS.setObjectName("CIMS")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(280, 320, 541, 61))
        self.lineEdit.setObjectName("lineEdit")
        self.Signin = QtWidgets.QPushButton(self.centralwidget)
        self.Signin.setGeometry(QtCore.QRect(890, 320, 93, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Signin.setFont(font)
        self.Signin.setObjectName("Signin")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 440, 541, 61))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.Signup = QtWidgets.QPushButton(self.centralwidget)
        self.Signup.setGeometry(QtCore.QRect(890, 440, 93, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Signup.setFont(font)
        self.Signup.setObjectName("Signup")
        SignIn.setCentralWidget(self.centralwidget)

        self.retranslateUi(SignIn)
        QtCore.QMetaObject.connectSlotsByName(SignIn)

    def retranslateUi(self, SignIn):
        _translate = QtCore.QCoreApplication.translate
        SignIn.setWindowTitle(_translate("SignIn", "Sign In"))
        self.CIMS.setText(_translate("SignIn", "CIMS"))
        self.Signin.setText(_translate("SignIn", "Sign in"))
        self.Signup.setText(_translate("SignIn", "Sign up"))
