# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\20212\software\implement\CIMS_project\UI\TotalInfoWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TotalInfoWindow(object):
    def setupUi(self, TotalInfoWindow):
        TotalInfoWindow.setObjectName("TotalInfoWindow")
        TotalInfoWindow.resize(964, 914)
        TotalInfoWindow.setIconSize(QtCore.QSize(16, 16))
        self.centralwidget = QtWidgets.QWidget(TotalInfoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.VaccineInfo = QtWidgets.QPushButton(self.centralwidget)
        self.VaccineInfo.setGeometry(QtCore.QRect(20, 10, 211, 131))
        self.VaccineInfo.setObjectName("VaccineInfo")
        self.CorronaInfo = QtWidgets.QPushButton(self.centralwidget)
        self.CorronaInfo.setGeometry(QtCore.QRect(260, 10, 211, 131))
        self.CorronaInfo.setObjectName("CorronaInfo")
        self.EventInfo = QtWidgets.QPushButton(self.centralwidget)
        self.EventInfo.setGeometry(QtCore.QRect(500, 10, 211, 131))
        self.EventInfo.setObjectName("EventInfo")
        self.Infected_personInfo = QtWidgets.QPushButton(self.centralwidget)
        self.Infected_personInfo.setGeometry(QtCore.QRect(740, 10, 211, 131))
        self.Infected_personInfo.setObjectName("Infected_personInfo")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(790, 160, 161, 711))
        self.listWidget_2.setObjectName("listWidget_2")
        self.alarmbutton = QtWidgets.QPushButton(self.centralwidget)
        self.alarmbutton.setGeometry(QtCore.QRect(870, 880, 81, 23))
        self.alarmbutton.setObjectName("alarmbutton")
        self.alarmtext = QtWidgets.QLabel(self.centralwidget)
        self.alarmtext.setGeometry(QtCore.QRect(770, 880, 91, 20))
        self.alarmtext.setText("")
        self.alarmtext.setObjectName("alarmtext")
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(30, 880, 81, 31))
        self.Back.setObjectName("Back")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(25, 161, 741, 711))
        self.listWidget.setObjectName("listWidget")
        TotalInfoWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TotalInfoWindow)
        QtCore.QMetaObject.connectSlotsByName(TotalInfoWindow)

    def retranslateUi(self, TotalInfoWindow):
        _translate = QtCore.QCoreApplication.translate
        TotalInfoWindow.setWindowTitle(_translate("TotalInfoWindow", "CIMS"))
        self.VaccineInfo.setText(_translate("TotalInfoWindow", "백신"))
        self.CorronaInfo.setText(_translate("TotalInfoWindow", "코로나"))
        self.EventInfo.setText(_translate("TotalInfoWindow", "비대면 행사"))
        self.Infected_personInfo.setText(_translate("TotalInfoWindow", "확진자"))
        self.alarmbutton.setText(_translate("TotalInfoWindow", "알림"))
        self.Back.setText(_translate("TotalInfoWindow", "Back"))
