# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\20212\software\implement\CIMS_project\UI\UserMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserMenu(object):
    def setupUi(self, UserMenu):
        UserMenu.setObjectName("UserMenu")
        UserMenu.resize(800, 615)
        self.centralwidget = QtWidgets.QWidget(UserMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.DisplayInfo = QtWidgets.QPushButton(self.centralwidget)
        self.DisplayInfo.setGeometry(QtCore.QRect(600, 120, 171, 81))
        self.DisplayInfo.setObjectName("DisplayInfo")
        self.SearchVisitPlace = QtWidgets.QPushButton(self.centralwidget)
        self.SearchVisitPlace.setGeometry(QtCore.QRect(600, 260, 171, 81))
        self.SearchVisitPlace.setObjectName("SearchVisitPlace")
        self.SearchImpactedPlace = QtWidgets.QPushButton(self.centralwidget)
        self.SearchImpactedPlace.setGeometry(QtCore.QRect(600, 400, 171, 81))
        self.SearchImpactedPlace.setObjectName("SearchImpactedPlace")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(580, 50, 20, 501))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(770, 50, 20, 501))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(590, 40, 191, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(590, 540, 191, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        UserMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserMenu)
        QtCore.QMetaObject.connectSlotsByName(UserMenu)

    def retranslateUi(self, UserMenu):
        _translate = QtCore.QCoreApplication.translate
        UserMenu.setWindowTitle(_translate("UserMenu", "Menu"))
        self.DisplayInfo.setText(_translate("UserMenu", "DisplayInfo"))
        self.SearchVisitPlace.setText(_translate("UserMenu", "Search Visit Place"))
        self.SearchImpactedPlace.setText(_translate("UserMenu", "Search Impacted Place"))
