# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\20212\software\implement\CIMS_project\UI\ViewInformation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewInformationDialog(object):
    def setupUi(self, ViewInformationDialog):
        ViewInformationDialog.setObjectName("ViewInformationDialog")
        ViewInformationDialog.resize(1280, 720)
        ViewInformationDialog.setMinimumSize(QtCore.QSize(1280, 720))
        self.ContentsTextEdit = QtWidgets.QTextEdit(ViewInformationDialog)
        self.ContentsTextEdit.setGeometry(QtCore.QRect(0, 0, 851, 511))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.ContentsTextEdit.setFont(font)
        self.ContentsTextEdit.setObjectName("ContentsTextEdit")
        self.ReportButton = QtWidgets.QPushButton(ViewInformationDialog)
        self.ReportButton.setGeometry(QtCore.QRect(710, 530, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.ReportButton.setFont(font)
        self.ReportButton.setObjectName("ReportButton")

        self.retranslateUi(ViewInformationDialog)
        QtCore.QMetaObject.connectSlotsByName(ViewInformationDialog)

    def retranslateUi(self, ViewInformationDialog):
        _translate = QtCore.QCoreApplication.translate
        ViewInformationDialog.setWindowTitle(_translate("ViewInformationDialog", "View Information"))
        self.ReportButton.setText(_translate("ViewInformationDialog", "Report"))
