# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\20212\software\implement\CIMS_project\UI\VisitPlace List.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VisitPlaceList(object):
    def setupUi(self, VisitPlaceList):
        VisitPlaceList.setObjectName("VisitPlaceList")
        VisitPlaceList.resize(682, 641)
        self.SearchButton = QtWidgets.QPushButton(VisitPlaceList)
        self.SearchButton.setGeometry(QtCore.QRect(530, 560, 131, 61))
        self.SearchButton.setObjectName("SearchButton")
        self.textBrowser = QtWidgets.QTextBrowser(VisitPlaceList)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 621, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.VisitPlaceListScroll = QtWidgets.QSlider(VisitPlaceList)
        self.VisitPlaceListScroll.setGeometry(QtCore.QRect(650, 20, 22, 521))
        self.VisitPlaceListScroll.setOrientation(QtCore.Qt.Vertical)
        self.VisitPlaceListScroll.setObjectName("VisitPlaceListScroll")

        self.retranslateUi(VisitPlaceList)
        QtCore.QMetaObject.connectSlotsByName(VisitPlaceList)

    def retranslateUi(self, VisitPlaceList):
        _translate = QtCore.QCoreApplication.translate
        VisitPlaceList.setWindowTitle(_translate("VisitPlaceList", "Visit Place List"))
        self.SearchButton.setText(_translate("VisitPlaceList", "Search"))
